### ISSUE TITLE
movim crash on fresh install debian 8

### ISSUE THREAD

**Issue by bachy** [movim/movim_ynh#18]
hello, it's me again
i'm sorry to bother you :/
I installed an other ynh server today for my school
i specially want to test movim in a art school context with my students
so i am on a vps from ovh, fresh debian 8, fresh yunohost, every thing is working good, jappix is working so i guess metronome to
but movim is crashing if i try to go in it, 500 internal server error
I still can't find any clue on logs on the server, nginx, metronome, last_log, nothing ...

**Comment by bachy** [comment]
i removed the app, reinstalled it, idem
movim interface appears for a second with (i think, its really quick) a oups message, and then WSOD

**Comment by bachy** [comment]
ok i got something from syslog
```
Jan 28 20:10:22 vps223924 movim[2644]: movim.ERROR: Undefined offset: 1 [] []
Jan 28 20:10:22 vps223924 movim[2645]: movim.ERROR: Undefined offset: 1 [] []
Jan 28 20:10:22 vps223924 movim[2605]: #033[0m#033[33mcZ7EsmU49NQkJwDDmtou1n7KmnbeIkkO#033[0m : #033[32m271 connected
Jan 28 20:10:22 vps223924 movim[2605]: #033[0m#033[33mcZ7EsmU49NQkJwDDmtou1n7KmnbeIkkO#033[0m widgets before : 2.8425140 MB
Jan 28 20:10:22 vps223924 movim[2605]: #033[33mcZ7EsmU49NQkJwDDmtou1n7KmnbeIkkO#033[0m widgets : 4.8357849 MB
Jan 28 20:10:23 vps223924 movim[3140]: movim.ERROR: Invalid argument supplied for foreach() [] []
Jan 28 20:10:23 vps223924 movim[2605]: #033[33mcZ7EsmU49NQkJwDDmtou1n7KmnbeIkkO#033[0m : #033[34mlinker launched#033[0m
Jan 28 20:10:23 vps223924 movim[2605]: #033[33mcZ7EsmU49NQkJwDDmtou1n7KmnbeIkkO#033[0m launched : 5.9096985 MB
Jan 28 20:10:23 vps223924 moxl[3140]: moxl.DEBUG: Handler : Memory instance not found for  [] []
Jan 28 20:10:23 vps223924 moxl[3140]: moxl.DEBUG: Handler : Not an XMPP ACK [] []
Jan 28 20:10:23 vps223924 moxl[3140]: moxl.DEBUG: Handler : Searching a payload for "streamfeatures:", "d9017180bc56364e7ba2bb1e493994b8" [] []
Jan 28 20:10:23 vps223924 moxl[3140]: moxl.DEBUG: Handler : This event is not listed [] []
Jan 28 20:10:23 vps223924 moxl[3140]: moxl.DEBUG: Handler : Searching a payload for "starttls:urn:ietf:params:xml:ns:xmpp-tls", "b95746de5ddc3fa5fbf28906c017d9d8" [] []
Jan 28 20:10:23 vps223924 moxl[3140]: moxl.DEBUG: Handler : Searching a payload for "required:", "ac67ede5a84eb5a1add7ff4440e9a485" [] []
Jan 28 20:10:23 vps223924 moxl[3140]: moxl.DEBUG: Handler : This event is not listed [] []
Jan 28 20:10:23 vps223924 movim[2605]: #033[33mcZ7EsmU49NQkJwDDmtou1n7KmnbeIkkO#033[0m : #033[31mstream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
Jan 28 20:10:23 vps223924 movim[2605]: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed#033[0m
Jan 28 20:10:23 vps223924 movim[2605]: #033[33mcZ7EsmU49NQkJwDDmtou1n7KmnbeIkkO#033[0m : #033[31mlinker killed
Jan 28 20:10:23 vps223924 movim[2605]: #033[0m#033[33mcZ7EsmU49NQkJwDDmtou1n7KmnbeIkkO#033[0m : #033[31m271 deconnected
Jan 28 20:10:23 vps223924 movim[2644]: movim.DEBUG: Locale: Translation key "Route not set for the page %s" not found [] []
Jan 28 20:10:23 vps223924 movim[2644]: movim.ERROR: Uncaught exception 'Exception' in /var/www/movim/system/Route.php:93 Stack trace: #0 /var/www/movim/system/controllers/BaseController.php(61): Route::urlize('') #1 /var/www/movim/app/controllers/DisconnectController.php(11): BaseController->redirect('') #2 /var/www/movim/system/controllers/FrontController.php(54): DisconnectController->dispatch() #3 /var/www/movim/system/controllers/FrontController.php(22): FrontController->runRequest('disconnect') #4 /var/www/movim/index.php(53): FrontController->handle() #5 {main}   thrown [] []
```

**Comment by src386** [comment]
Hello,

    "le format de l'identifiant n'est pas correct"

This message is just a warning. It is indeed because of ssowat.

I'm not sure what's the origin of your problem, maybe bad SSL certificate or unknown locale ? I will ask to the Movim team.

**Comment by bachy** [comment]
ok, maybe it's related to this issue : https://github.com/movim/movim/issues/6
apprently movim can't run with slefsigned certificats
i'll try let's encrypt tomorrow.

**Comment by src386** [comment]
I'm not sure it's a blocking problem, but yeah you can try.

**Comment by bachy** [comment]
ok i installed letsencrypt with this package https://github.com/alexAubin/letsencrypt_ynh
now movim is running fine!!
selfsigned certificat was the probleme

**Comment by src386** [comment]
Excellent news !!!
